generate_pars:
	gcc -o $@.exe $@.c

pointers:
	gcc -o $@.exe $@.c

rain_water:
	gcc -o $@.exe $@.c

check_regex:
	gcc -o $@.exe $@.c

din_phil:
	gcc -o $@.exe $@.c

dining_philosophers:
	gcc -o $@.exe $@.c

fizz_buzz:
	gcc -o fizz_buzz.exe fizz_buzz.c

threads:
	gcc -o $@.exe $@.c